baseURL: "https://hungdong.land"
languageCode: en-us
title: Hừng Đông Land
theme: PaperMod
paginate: 8

params:
  env: production
  homeInfoParams:
    Title: "Xin chào"
    Content: "Chào mừng các anh chị đã đến với sản phẩm bất động sản Xanh tại Ecopark. Con người được sinh ra từ thiên nhiên, và không thể tách rời khỏi thiên nhiên.
    Cũng vì lẽ đó bất động sản Ecopark mạng một dấu ấn thiên nhiên đậm nét, dấu ấn Xanh, yên bình và được nuôi dưỡng, sinh trưởng. 
    Rất hân hạnh được đón tiếp và tư vấn phục vụ anh chị những sản phẩm xanh tại Ecopark. Chúc anh chị gặp nhiều may mắn và sức khỏe. Cảm ơn anh chị rất nhiều! 
    **Xin mời gọi: 098.388.6961, Ms Tú.**"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nhagiaodich_com"
    - name: tiktok
      url: "https://tiktok.com/@nhagiaodich_com"
    - name: facebook
      url: "https://www.facebook.com/nhagiaodichcom"
    - name: youtube
      url: "https://www.youtube.com/@nhagiaodich_com"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    # - identifier: categories
    #   name: Phân loại
    #   url: /categories/
    #   weight: 10
    - identifier: categories1
      name: Bất động sản giao bán
      url: /categories/Bất động sản giao bán/
      weight: 10
    - identifier: categories2
      name: Bất động sản cho thuê
      url: /categories/Bất động sản cho thuê/
      weight: 20
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 20
    - identifier: archives
      name: Lưu trữ
      url: /archives/
      weight: 30
    - identifier: search
      name: Tìm kiếm
      url: /search/
      weight: 40
